SPOOL C:\temp\Execution01.log

-- 1. CREATION DES TABLESPACES

CREATE TABLESPACE DATA_SOF_PISE
DATAFILE 
'C:/Apps/oradata/Data_Sof_Pise_1.dbf' SIZE 256 m,
'C:/Apps/oradata/Data_Sof_Pise_2.dbf' SIZE 256 m,
'C:/Apps/oradata/Data_Sof_Pise_3.dbf' SIZE 256 m
 SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE INDEX_SOF_PISE
DATAFILE 
'C:/Apps/oradata/Index_Sof_Pise_1.dbf' SIZE 128 m,
'C:/Apps/oradata/Index_Sof_Pise_2.dbf' SIZE 256 m
SEGMENT SPACE MANAGEMENT AUTO;

-- attribution des droits des tablespaces a l'admin

ALTER USER administrateur DEFAULT TABLESPACE DATA_SOF_PISE ;
ALTER USER administrateur QUOTA UNLIMITED ON DATA_SOF_PISE ;
ALTER USER administrateur DEFAULT TABLESPACE INDEX_SOF_PISE ;
ALTER USER administrateur QUOTA UNLIMITED ON INDEX_SOF_PISE ;

-- connexion de l'admin

connect administrateur/admin123

SHOW USER

-- 2. CREATION DE TOUTES LES TABLES

-- UTILISATEURS

CREATE TABLE ROLE_UTILISATEUR (
    id_role_user VARCHAR2(20) NOT NULL,
    libelle_role_user VARCHAR2(50) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE UTILISATEURS (
    id_utilisateur VARCHAR2(20) NOT NULL,
    nom_utilisateur VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_ROLE_USER (
    id_utilisateur VARCHAR2(20) NOT NULL,
    id_role_user VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

-- CATALOGUE PRODUITS

CREATE TABLE MARQUE (
    id_marque VARCHAR2(20) NOT NULL,
    nom_marque VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE CATEGORIE_PRODUIT (
    id_cat_produit VARCHAR2(20) NOT NULL,
    libelle_cat_produit VARCHAR2(100) NOT NULL,
    id_cat_produit_PARENT VARCHAR2(20)
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE PRODUIT (
    SKU_produit VARCHAR2(20) NOT NULL,
    nom_produit VARCHAR2(100) NOT NULL,
    description_produit VARCHAR2(1000),
    prix_achat_ht NUMBER(10,2),
    prix_vente_ht NUMBER(10,2),
    taux_tva NUMBER(5,2),
    id_cat_produit VARCHAR2(20) NOT NULL,
    id_marque VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE VARIANTE (
    SKU_variante VARCHAR2(20) NOT NULL,
    libelle_variante VARCHAR2(200),
    poids_unitaire_variante NUMBER(8,3),
    SKU_produit VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE IMAGE_PRODUIT (
    id_image VARCHAR2(20) NOT NULL,
    nom_image VARCHAR2(200) NOT NULL,
    emplacement_image VARCHAR2(500), -- URL ou chemin d'accès
    SKU_produit VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_IMAGE (
    SKU_produit VARCHAR2(20) NOT NULL,
    id_image VARCHAR2(20) NOT NULL,
    est_principale NUMBER(1) CHECK (est_principale IN (0,1)) NOT NULL 
    -- syntaxe trouvé sur internet : CHECK permet de limiter les valeurs autorisées , ici 0 = non, 1 = oui
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE ETIQUETTE_PRODUIT (
    id_tag_produit VARCHAR2(20) NOT NULL,
    libelle_tag_produit VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_ETIQUETTE (
    SKU_produit VARCHAR2(20) NOT NULL,
    id_tag_produit VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE ATTRIBUT_PRODUIT (
    id_attribut_pdt VARCHAR2(20) NOT NULL,
    type_attribut_pdt VARCHAR2(80) NOT NULL,
    valeur_attribut_pdt VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_POUR_ATTRIBUT (
    SKU_variante VARCHAR2(20) NOT NULL,
    id_attribut_pdt VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE CATALOGUE (
    id_catalogue VARCHAR2(20) NOT NULL,
    libelle_catalogue VARCHAR2(100) NOT NULL,
    date_catalogue DATE
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE APPARTENANCE_CATALOGUE (
    SKU_produit VARCHAR2(20) NOT NULL,
    id_catalogue VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

-- GESTION DES STOCKS

CREATE TABLE STATUT_PRODUIT (
    id_statut_produit VARCHAR2(20) NOT NULL,
    libelle_statut_produit VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_STATUT_STOCK (
    id_statut_produit VARCHAR2(20) NOT NULL,
    SKU_variante VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE ENTREPOT (
    id_entrepot VARCHAR2(20) NOT NULL,
    nom_entrepot VARCHAR2(100) NOT NULL,
    adresse_entrepot VARCHAR2(300) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE STOCKER (
    id_entrepot VARCHAR2(20) NOT NULL,
    SKU_variante VARCHAR2(20) NOT NULL,
    quantite_produit NUMBER(10) NOT NULL,
    seuil_reapprovisionnement NUMBER(10) NOT NULL,
    stock_securite NUMBER(10) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE TYPE_MVMT_STOCK (
    id_type_mvmt_stock VARCHAR2(20) NOT NULL,
    libelle_type_mvmt_stock VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE MOUVEMENT_STOCK (
    id_mouvement_stock VARCHAR2(20) NOT NULL,
    quantite_mouvement NUMBER(10) NOT NULL,
    date_mouvement_stock DATE NOT NULL,
    motif_mouvement_stock VARCHAR2(200),
    SKU_variante VARCHAR2(20) NOT NULL,
    id_entrepot VARCHAR2(20) NOT NULL,
    id_type_mvmt_stock VARCHAR2(20) NOT NULL,
    id_utilisateur VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE INVENTAIRE_STOCK (
    id_inventaire VARCHAR2(20) NOT NULL,
    periode_inventaire VARCHAR2(50) NOT NULL,
    id_entrepot VARCHAR2(20) NOT NULL,
    id_utilisateur VARCHAR2(20) NOT NULL,
    SKU_variante VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_POUR_INVENTAIRE (
    id_inventaire VARCHAR2(20) NOT NULL,
    SKU_variante VARCHAR2(20) NOT NULL,
    stock_theorique NUMBER(10) NOT NULL,
    stock_physique NUMBER(10) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE TRANSFERT_INTERENTREPOT (
    id_transfert VARCHAR2(20) NOT NULL,
    date_demande_transfert DATE NOT NULL,
    date_reception_transfert DATE,
    id_entrepot_SOURCE_TRANSFERT VARCHAR2(20) NOT NULL,
    id_entrepot_DEST_TRANSFERT VARCHAR2(20) NOT NULL,
    id_mouvement_stock VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

-- GESTION DES FOURNISSEURS

CREATE TABLE FOURNISSEUR (
    ref_fournisseur VARCHAR2(20) NOT NULL,
    nom_fournisseur VARCHAR2(150) NOT NULL,
    adresse_fournisseur VARCHAR2(300),
    SIRET NUMBER(14),
    num_tva_intracomm VARCHAR2(20)
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE FOURNIR (
    ref_fournisseur VARCHAR2(20) NOT NULL,
    SKU_variante VARCHAR2(20) NOT NULL,
    prix_achat_produit NUMBER(10,2) NOT NULL,
    delai_livraison NUMBER(4) NOT NULL,
    quantite_min_cde NUMBER(4) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE STATUT_CDE_FOUR (
    id_statut_cde VARCHAR2(20) NOT NULL,
    libelle_statut_cde VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE COMMANDE_FOURNISSEUR (
    id_commande_four VARCHAR2(20) NOT NULL,
    date_commande DATE NOT NULL,
    total_ht_cde_fournisseur NUMBER(12,2) NOT NULL,
    total_tva_cde_fournisseur NUMBER(12,2) NOT NULL,
    total_ttc_cde_fournisseur NUMBER(12,2) NOT NULL,
    ref_fournisseur VARCHAR2(20) NOT NULL,
    id_utilisateur VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_STT_CDE (
    id_commande_four VARCHAR2(20) NOT NULL,
    id_statut_cde VARCHAR2(20) NOT NULL,
    date_changement_statut DATE NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE LIGNE_CDE_FOUR (
    id_ligne_cde_four VARCHAR2(20) NOT NULL,
    qte_cde_fournisseur NUMBER(4) NOT NULL,
    id_commande_four VARCHAR2(20) NOT NULL,
    SKU_variante VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE RECEPTION_CDE_FOUR (
    SKU_variante VARCHAR2(20) NOT NULL,
    id_ligne_cde_four VARCHAR2(20) NOT NULL,
    date_reception_four DATE NOT NULL,
    quantite_reception NUMBER(4) NOT NULL
) TABLESPACE DATA_SOF_PISE;

-- GESTION DES CLIENTS

CREATE TABLE SEGMENT_CLIENT (
    id_segment VARCHAR2(20) NOT NULL,
    libelle_segment VARCHAR2(100) NOT NULL,
    est_defaut NUMBER(1) CHECK (est_defaut IN (0,1))
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE CLIENT (
    email VARCHAR2(150) NOT NULL,
    mdp_hashe VARCHAR2(255) NOT NULL,
    nom_client VARCHAR2(100) NOT NULL,
    prenom_client VARCHAR2(100) NOT NULL,
    date_inscription DATE,
    id_segment VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE ADRESSE_CLIENT (
    id_adresse VARCHAR2(20) NOT NULL,
    numero_adr VARCHAR2(10),
    nom_rue VARCHAR2(200) NOT NULL,
    code_postale_adr VARCHAR2(10) NOT NULL,
    ville_adr VARCHAR2(100) NOT NULL,
    pays_adr VARCHAR2(100),
    complement_adr VARCHAR2(200)
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_ADRESSE (
    email VARCHAR2(150) NOT NULL,
    id_adresse VARCHAR2(20) NOT NULL,
    type_adresse VARCHAR2(50) NOT NULL, -- Facturation ou Livraison
    est_defaut NUMBER(1) CHECK (est_defaut IN (0,1))
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE COMPTE_FIDELITE (
    id_compte_fid VARCHAR2(20) NOT NULL,
    solde_points_fid NUMBER(10) NOT NULL,
    total_points_fid NUMBER(10)  NOT NULL,
    email VARCHAR2(150) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE HISTORIQUE_POINTS (
    id_historique_pts_fid VARCHAR2(20) NOT NULL,
    date_event_pts_fid DATE,
    type_mvmt_pts_fid VARCHAR2(50) NOT NULL,
    nb_pts_fid NUMBER(10) NOT NULL,
    motif_mvmt_pts_fid VARCHAR2(200),
    id_compte_fid VARCHAR2(20) NOT NULL,
    num_fact_client VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE BON_REDUCTION (
    id_bon_reduction VARCHAR2(20) NOT NULL,
    montant_bon_reduc NUMBER(10,2) NOT NULL,
    date_emission_bon_reduc DATE NOT NULL,
    date_limite_bon_reduc DATE,
    id_compte_fid VARCHAR2(20) NOT NULL,
    id_historique_pts_fid VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE APPLIQUER_BON_REDUC (
    num_cde_client VARCHAR2(20) NOT NULL,
    id_bon_reduction VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

-- GESTION DES COMMANDES

CREATE TABLE STATUT_CDE_CLIENT (
    id_statut_cde_client VARCHAR2(20) NOT NULL,
    libelle_statut_cde_client VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_STATUT_CDE_CLIENT (
    num_cde_client VARCHAR2(20) NOT NULL,
    id_statut_cde_client VARCHAR2(20) NOT NULL,
    date_changement_statut_cde_client DATE NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE COMMANDE_CLIENT (
    num_cde_client VARCHAR2(20) NOT NULL,
    date_cde_client DATE NOT NULL,
    total_ht_cde_client NUMBER(12,2) NOT NULL,
    total_tva_cde_client NUMBER(12,2) NOT NULL,
    total_ttc_cde_client NUMBER(12,2) NOT NULL,
    statut_paiement VARCHAR2(50) NOT NULL,
    mode_paiement VARCHAR2(50),
    date_paiement DATE,
    email VARCHAR2(150) NOT NULL,
    id_adresse_LIVRER_A VARCHAR2(20) NOT NULL,
    id_adresse_FACTURER_A VARCHAR2(20) NOT NULL,
    id_utilisateur VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE LIGNE_CDE_CLIENT (
    id_ligne_cde_client VARCHAR2(20) NOT NULL,
    qte_cde_client NUMBER(4) NOT NULL,
    prix_unitaire_ttc NUMBER(10,2) NOT NULL,
    totalttc_ligne_cdeclient NUMBER(10,2) NOT NULL,
    totaltva_ligne_cdeclient NUMBER(10,2),
    num_cde_client VARCHAR2(20) NOT NULL,
    SKU_variante VARCHAR2(20) NOT NULL,
    id_entrepot VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE FACTURE_CLIENT (
    num_fact_client VARCHAR2(20) NOT NULL,
    date_fact_client DATE NOT NULL,
    total_ht NUMBER(12,2) NOT NULL,
    total_tva NUMBER(12,2) NOT NULL,
    total_ttc NUMBER(12,2) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE GENERER_FACT (
    num_fact_client VARCHAR2(20) NOT NULL,
    num_cde_client VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

-- POLITIQUE TARIFAIRE & PROMOTIONS

CREATE TABLE TYPE_PROMOTION (
    id_type_promo VARCHAR2(20) NOT NULL,
    libelle_type_promo VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE PROMOTION (
    code_promo VARCHAR2(20) NOT NULL,
    montant_promo NUMBER(8,2) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    quantite_limite NUMBER(10),
    usage_code_promo NUMBER(10) DEFAULT 0 NOT NULL,
-- syntaxe trouve sur internet : DEFAULT permet d'attribuer automatiquement une valeur si aucune n'est saisie , ici 0 par defaut
    id_type_promo VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE CONDITIONS_PROMO (
    id_condition_promo VARCHAR2(20) NOT NULL,
    libelle_condition_promo VARCHAR2(100) NOT NULL,
    detail_condition_promo VARCHAR2(300)
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE AVOIR_CONDITION_PROMO (
    code_promo VARCHAR2(20) NOT NULL,
    id_condition_promo VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE APPLIQUE_CDE_PROMO (
    code_promo VARCHAR2(20) NOT NULL,
    num_cde_client VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE APPLIQUE_PROMO_CAT (
    id_cat_produit VARCHAR2(20) NOT NULL,
    code_promo VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE APPLIQUE_PROMO_MARQUE (
    id_marque VARCHAR2(20) NOT NULL,
    code_promo VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE APPLIQUE_PROMO_CATALOG (
    id_catalogue VARCHAR2(20) NOT NULL,
    code_promo VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE APPLIQUE_PROMO_PDT (
    code_promo VARCHAR2(20) NOT NULL,
    SKU_produit VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

-- LOGISTIQUE & EXPEDITION

CREATE TABLE TRANSPORTEUR (
    id_transporteur VARCHAR2(20) NOT NULL,
    nom_transporteur VARCHAR2(100) NOT NULL,
    adr_transporteur VARCHAR2(300)
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE GRILLE_TARIFAIRE_TPS (
    id_tarif_tps VARCHAR2(20) NOT NULL,
    poids_min_tps NUMBER(8,3) NOT NULL,
    poids_max_tps NUMBER(8,3) NOT NULL,
    zone_geo_tps VARCHAR2(80) NOT NULL,
    prix_tps_ht NUMBER(8,2) NOT NULL,
    prix_tps_ttc NUMBER(8,2) NOT NULL,
    prix_tps_tva NUMBER(8,2) NOT NULL,
    id_transporteur VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE COLIS (
    num_suivi_colis VARCHAR2(20) NOT NULL,
    date_envoi_colis DATE,
    date_reception_colis DATE,
    poids_colis NUMBER(8,3),
    id_utilisateur VARCHAR2(20) NOT NULL,
    id_transporteur VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE CONTENIR_COLIS (
    num_suivi_colis VARCHAR2(20) NOT NULL,
    id_ligne_cde_client VARCHAR2(20) NOT NULL,
    qte_expediee_client NUMBER(4) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE PRIS_EN_CHARGE_TPS (
    num_suivi_colis VARCHAR2(20) NOT NULL,
    id_transporteur VARCHAR2(20) NOT NULL,
    tarif_tps_colis NUMBER(8,2) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE HISTORIQUE_EVENT_COLIS (
    id_event_colis VARCHAR2(20) NOT NULL,
    type_event_colis VARCHAR2(80) NOT NULL,
    date_event_colis DATE NOT NULL,
    commentaire_event_colis VARCHAR2(500),
    num_suivi_colis VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

-- AVIS CLIENTS

CREATE TABLE AVIS_CLIENT (
    id_avis VARCHAR2(20) NOT NULL,
    note_avis NUMBER(1) CHECK (note_avis BETWEEN 1 AND 5) NOT NULL,
    titre_avis VARCHAR2(200),
    commentaire_avis VARCHAR2(4000),
    date_avis DATE NOT NULL,
    email VARCHAR2(150) NOT NULL,
    SKU_variante VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE MODERATION_AVIS (
    id_type_mod_avis VARCHAR2(20) NOT NULL,
    libelle_type_mod_avis VARCHAR2(100) NOT NULL
) TABLESPACE DATA_SOF_PISE;

CREATE TABLE HISTORIQUE_MOD_AVIS (
    id_histo_mod_avis VARCHAR2(20) NOT NULL,
    date_mod_avis DATE NOT NULL,
    id_avis VARCHAR2(20) NOT NULL,
    id_type_mod_avis VARCHAR2(20) NOT NULL,
    id_utilisateur VARCHAR2(20) NOT NULL
) TABLESPACE DATA_SOF_PISE;

-- 3. CREATION DE TOUTES LES CLES PRIMAIRES

-- PK UTILISATEURS
ALTER TABLE ROLE_UTILISATEUR ADD CONSTRAINT ROLE_UTILISATEUR_PK 
    PRIMARY KEY (id_role_user) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE UTILISATEURS ADD CONSTRAINT UTILISATEURS_PK 
    PRIMARY KEY (id_utilisateur) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_ROLE_USER ADD CONSTRAINT AVOIR_ROLE_USER_PK 
    PRIMARY KEY (id_utilisateur, id_role_user) USING INDEX TABLESPACE INDEX_SOF_PISE;

-- PK CATALOGUE PRODUITS
ALTER TABLE MARQUE ADD CONSTRAINT MARQUE_PK 
    PRIMARY KEY (id_marque) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE CATEGORIE_PRODUIT ADD CONSTRAINT CATEGORIE_PRODUIT_PK 
    PRIMARY KEY (id_cat_produit) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE PRODUIT ADD CONSTRAINT PRODUIT_PK 
    PRIMARY KEY (SKU_produit) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE VARIANTE ADD CONSTRAINT VARIANTE_PK 
    PRIMARY KEY (SKU_variante) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE IMAGE_PRODUIT ADD CONSTRAINT IMAGE_PRODUIT_PK 
    PRIMARY KEY (id_image) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_IMAGE 
    ADD CONSTRAINT AVOIR_IMAGE_PK PRIMARY KEY (SKU_produit, id_image) 
    USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE ETIQUETTE_PRODUIT 
    ADD CONSTRAINT ETIQUETTE_PRODUIT_PK PRIMARY KEY (id_tag_produit) 
    USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_ETIQUETTE 
    ADD CONSTRAINT AVOIR_ETIQUETTE_PK PRIMARY KEY (SKU_produit, id_tag_produit) 
    USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE ATTRIBUT_PRODUIT 
    ADD CONSTRAINT ATTRIBUT_PRODUIT_PK PRIMARY KEY (id_attribut_pdt) 
    USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_POUR_ATTRIBUT 
    ADD CONSTRAINT AVOIR_POUR_ATTRIBUT_PK PRIMARY KEY (SKU_variante, id_attribut_pdt) 
    USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE CATALOGUE 
    ADD CONSTRAINT CATALOGUE_PK PRIMARY KEY (id_catalogue) 
    USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE APPARTENANCE_CATALOGUE 
    ADD CONSTRAINT APPARTENANCE_CAT_PK PRIMARY KEY (SKU_produit, id_catalogue) 
    USING INDEX TABLESPACE INDEX_SOF_PISE;

-- PK GESTION DES STOCKS
ALTER TABLE STATUT_PRODUIT ADD CONSTRAINT STATUT_PRODUIT_PK 
    PRIMARY KEY (id_statut_produit) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_STATUT_STOCK ADD CONSTRAINT AVOIR_STATUT_STOCK_PK 
    PRIMARY KEY (id_statut_produit, SKU_variante) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE ENTREPOT ADD CONSTRAINT ENTREPOT_PK 
    PRIMARY KEY (id_entrepot) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE STOCKER ADD CONSTRAINT STOCKER_PK 
    PRIMARY KEY (id_entrepot, SKU_variante) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE TYPE_MVMT_STOCK ADD CONSTRAINT TYPE_MVMT_STOCK_PK 
    PRIMARY KEY (id_type_mvmt_stock) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE MOUVEMENT_STOCK ADD CONSTRAINT MOUVEMENT_STOCK_PK 
    PRIMARY KEY (id_mouvement_stock) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE INVENTAIRE_STOCK ADD CONSTRAINT INVENTAIRE_STOCK_PK 
    PRIMARY KEY (id_inventaire) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_POUR_INVENTAIRE ADD CONSTRAINT AVOIR_POUR_INV_PK 
    PRIMARY KEY (id_inventaire, SKU_variante) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE TRANSFERT_INTERENTREPOT ADD CONSTRAINT TRANSFERT_PK 
    PRIMARY KEY (id_transfert) USING INDEX TABLESPACE INDEX_SOF_PISE;

-- PK GESTION DES FOURNISSEURS
ALTER TABLE FOURNISSEUR ADD CONSTRAINT FOURNISSEUR_PK 
    PRIMARY KEY (ref_fournisseur) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE FOURNIR ADD CONSTRAINT FOURNIR_PK 
    PRIMARY KEY (ref_fournisseur, SKU_variante) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE STATUT_CDE_FOUR ADD CONSTRAINT STATUT_CDE_FOUR_PK 
    PRIMARY KEY (id_statut_cde) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE COMMANDE_FOURNISSEUR ADD CONSTRAINT COMMANDE_FOUR_PK 
    PRIMARY KEY (id_commande_four) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_STT_CDE ADD CONSTRAINT AVOIR_STT_CDE_PK 
    PRIMARY KEY (id_commande_four, id_statut_cde) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE LIGNE_CDE_FOUR ADD CONSTRAINT LIGNE_CDE_FOUR_PK 
    PRIMARY KEY (id_ligne_cde_four) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE RECEPTION_CDE_FOUR ADD CONSTRAINT RECEPTION_CDE_FOUR_PK 
    PRIMARY KEY (SKU_variante, id_ligne_cde_four) USING INDEX TABLESPACE INDEX_SOF_PISE;

-- PK GESTION DES CLIENTS
ALTER TABLE SEGMENT_CLIENT ADD CONSTRAINT SEGMENT_CLIENT_PK 
    PRIMARY KEY (id_segment) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE CLIENT ADD CONSTRAINT CLIENT_PK 
    PRIMARY KEY (email) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE ADRESSE_CLIENT ADD CONSTRAINT ADRESSE_CLIENT_PK 
    PRIMARY KEY (id_adresse) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_ADRESSE ADD CONSTRAINT AVOIR_ADRESSE_PK 
    PRIMARY KEY (email, id_adresse) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE COMPTE_FIDELITE ADD CONSTRAINT COMPTE_FIDELITE_PK 
    PRIMARY KEY (id_compte_fid) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE HISTORIQUE_POINTS ADD CONSTRAINT HISTORIQUE_POINTS_PK 
    PRIMARY KEY (id_historique_pts_fid) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE BON_REDUCTION ADD CONSTRAINT BON_REDUCTION_PK 
    PRIMARY KEY (id_bon_reduction) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE APPLIQUER_BON_REDUC ADD CONSTRAINT APPLIQUER_BON_REDUC_PK 
    PRIMARY KEY (num_cde_client, id_bon_reduction) USING INDEX TABLESPACE INDEX_SOF_PISE;

-- PK GESTION DES COMMANDES
ALTER TABLE STATUT_CDE_CLIENT ADD CONSTRAINT STATUT_CDE_CLI_PK 
    PRIMARY KEY (id_statut_cde_client) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_STATUT_CDE_CLIENT ADD CONSTRAINT AV_STATUT_CDE_CLI_PK 
    PRIMARY KEY (num_cde_client, id_statut_cde_client) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE COMMANDE_CLIENT ADD CONSTRAINT COMMANDE_CLIENT_PK 
    PRIMARY KEY (num_cde_client) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE LIGNE_CDE_CLIENT ADD CONSTRAINT LIGNE_CDE_CLI_PK 
    PRIMARY KEY (id_ligne_cde_client) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE FACTURE_CLIENT ADD CONSTRAINT FACTURE_CLIENT_PK 
    PRIMARY KEY (num_fact_client) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE GENERER_FACT ADD CONSTRAINT GENERER_FACT_PK 
    PRIMARY KEY (num_fact_client, num_cde_client) USING INDEX TABLESPACE INDEX_SOF_PISE;

-- PK POLITIQUE TARIFAIRE & PROMOTIONS
ALTER TABLE TYPE_PROMOTION ADD CONSTRAINT TYPE_PROMO_PK 
    PRIMARY KEY (id_type_promo) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE PROMOTION ADD CONSTRAINT PROMOTION_PK 
    PRIMARY KEY (code_promo) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE CONDITIONS_PROMO ADD CONSTRAINT CONDITIONS_PROMO_PK 
    PRIMARY KEY (id_condition_promo) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE AVOIR_CONDITION_PROMO ADD CONSTRAINT AV_COND_PROMO_PK 
    PRIMARY KEY (code_promo, id_condition_promo) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE APPLIQUE_CDE_PROMO ADD CONSTRAINT APP_CDE_PROMO_PK 
    PRIMARY KEY (code_promo, num_cde_client) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE APPLIQUE_PROMO_CAT ADD CONSTRAINT APP_PROMO_CAT_PK 
    PRIMARY KEY (id_cat_produit, code_promo) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE APPLIQUE_PROMO_MARQUE ADD CONSTRAINT APP_PROMO_MARQUE_PK 
    PRIMARY KEY (id_marque, code_promo) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE APPLIQUE_PROMO_CATALOG ADD CONSTRAINT APP_PROMO_CATALOG_PK 
    PRIMARY KEY (id_catalogue, code_promo) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE APPLIQUE_PROMO_PDT ADD CONSTRAINT APP_PROMO_PDT_PK 
    PRIMARY KEY (code_promo, SKU_produit) USING INDEX TABLESPACE INDEX_SOF_PISE;

-- PK LOGISTIQUE & EXPEDITION
ALTER TABLE TRANSPORTEUR ADD CONSTRAINT TRANSPORTEUR_PK 
    PRIMARY KEY (id_transporteur) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE GRILLE_TARIFAIRE_TPS ADD CONSTRAINT GRILLE_TARIFAIRE_TPS_PK 
    PRIMARY KEY (id_tarif_tps) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE COLIS ADD CONSTRAINT COLIS_PK 
    PRIMARY KEY (num_suivi_colis) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE CONTENIR_COLIS ADD CONSTRAINT CONTENIR_COLIS_PK 
    PRIMARY KEY (num_suivi_colis, id_ligne_cde_client) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE PRIS_EN_CHARGE_TPS ADD CONSTRAINT PRIS_EN_CHARGE_TPS_PK 
    PRIMARY KEY (num_suivi_colis, id_transporteur) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE HISTORIQUE_EVENT_COLIS ADD CONSTRAINT HISTO_EVENT_COLIS_PK 
    PRIMARY KEY (id_event_colis) USING INDEX TABLESPACE INDEX_SOF_PISE;

-- PK AVIS CLIENTS
ALTER TABLE AVIS_CLIENT ADD CONSTRAINT AVIS_CLIENT_PK 
    PRIMARY KEY (id_avis) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE MODERATION_AVIS ADD CONSTRAINT MODERATION_AVIS_PK 
    PRIMARY KEY (id_type_mod_avis) USING INDEX TABLESPACE INDEX_SOF_PISE;

ALTER TABLE HISTORIQUE_MOD_AVIS ADD CONSTRAINT HISTO_MOD_AVIS_PK 
    PRIMARY KEY (id_histo_mod_avis) USING INDEX TABLESPACE INDEX_SOF_PISE;

-- 4. CREATION DE TOUTES LES CLES ETRANGERES

-- FK UTILISATEURS
ALTER TABLE AVOIR_ROLE_USER ADD CONSTRAINT AVOIR_ROLE_USER_UTIL_FK 
    FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEURS(id_utilisateur);

ALTER TABLE AVOIR_ROLE_USER ADD CONSTRAINT AVOIR_ROLE_USER_ROLE_FK 
    FOREIGN KEY (id_role_user) REFERENCES ROLE_UTILISATEUR(id_role_user);

-- FK CATALOGUE PRODUITS
ALTER TABLE CATEGORIE_PRODUIT ADD CONSTRAINT CAT_PROD_PARENT_FK 
    FOREIGN KEY (id_cat_produit_PARENT) REFERENCES CATEGORIE_PRODUIT(id_cat_produit);

ALTER TABLE PRODUIT ADD CONSTRAINT PRODUIT_CAT_FK 
    FOREIGN KEY (id_cat_produit) REFERENCES CATEGORIE_PRODUIT(id_cat_produit);

ALTER TABLE PRODUIT ADD CONSTRAINT PRODUIT_MARQUE_FK 
    FOREIGN KEY (id_marque) REFERENCES MARQUE(id_marque);

ALTER TABLE VARIANTE ADD CONSTRAINT VARIANTE_PROD_FK 
    FOREIGN KEY (SKU_produit) REFERENCES PRODUIT(SKU_produit);

ALTER TABLE IMAGE_PRODUIT ADD CONSTRAINT IMAGE_PRODUIT_FK 
    FOREIGN KEY (SKU_produit) REFERENCES PRODUIT(SKU_produit);

ALTER TABLE AVOIR_IMAGE ADD CONSTRAINT AV_IMG_PROD_FK 
    FOREIGN KEY (SKU_produit) REFERENCES PRODUIT(SKU_produit);

ALTER TABLE AVOIR_IMAGE ADD CONSTRAINT AV_IMG_IMG_FK 
    FOREIGN KEY (id_image) REFERENCES IMAGE_PRODUIT(id_image);

ALTER TABLE AVOIR_ETIQUETTE ADD CONSTRAINT AV_ETIQ_PROD_FK 
    FOREIGN KEY (SKU_produit) REFERENCES PRODUIT(SKU_produit);

ALTER TABLE AVOIR_ETIQUETTE ADD CONSTRAINT AV_ETIQ_TAG_FK 
    FOREIGN KEY (id_tag_produit) REFERENCES ETIQUETTE_PRODUIT(id_tag_produit);

ALTER TABLE AVOIR_POUR_ATTRIBUT ADD CONSTRAINT AV_ATTR_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE AVOIR_POUR_ATTRIBUT ADD CONSTRAINT AV_ATTR_ATTR_FK 
    FOREIGN KEY (id_attribut_pdt) REFERENCES ATTRIBUT_PRODUIT(id_attribut_pdt);

ALTER TABLE APPARTENANCE_CATALOGUE ADD CONSTRAINT APP_CAT_PROD_FK 
    FOREIGN KEY (SKU_produit) REFERENCES PRODUIT(SKU_produit);

ALTER TABLE APPARTENANCE_CATALOGUE ADD CONSTRAINT APP_CAT_CAT_FK 
    FOREIGN KEY (id_catalogue) REFERENCES CATALOGUE(id_catalogue);

-- FK GESTION DES STOCKS
ALTER TABLE AVOIR_STATUT_STOCK ADD CONSTRAINT AV_STATUT_STK_FK 
    FOREIGN KEY (id_statut_produit) REFERENCES STATUT_PRODUIT(id_statut_produit);

ALTER TABLE AVOIR_STATUT_STOCK ADD CONSTRAINT AV_STATUT_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE STOCKER ADD CONSTRAINT STOCKER_ENT_FK 
    FOREIGN KEY (id_entrepot) REFERENCES ENTREPOT(id_entrepot);

ALTER TABLE STOCKER ADD CONSTRAINT STOCKER_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE MOUVEMENT_STOCK ADD CONSTRAINT MVMT_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE MOUVEMENT_STOCK ADD CONSTRAINT MVMT_ENT_FK 
    FOREIGN KEY (id_entrepot) REFERENCES ENTREPOT(id_entrepot);

ALTER TABLE MOUVEMENT_STOCK ADD CONSTRAINT MVMT_TYPE_FK 
    FOREIGN KEY (id_type_mvmt_stock) REFERENCES TYPE_MVMT_STOCK(id_type_mvmt_stock);

ALTER TABLE MOUVEMENT_STOCK ADD CONSTRAINT MVMT_USER_FK 
    FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEURS(id_utilisateur);

ALTER TABLE INVENTAIRE_STOCK ADD CONSTRAINT INV_ENT_FK 
    FOREIGN KEY (id_entrepot) REFERENCES ENTREPOT(id_entrepot);

ALTER TABLE INVENTAIRE_STOCK ADD CONSTRAINT INV_USER_FK 
    FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEURS(id_utilisateur);

ALTER TABLE INVENTAIRE_STOCK ADD CONSTRAINT INV_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE AVOIR_POUR_INVENTAIRE ADD CONSTRAINT AV_INV_ID_FK 
    FOREIGN KEY (id_inventaire) REFERENCES INVENTAIRE_STOCK(id_inventaire);

ALTER TABLE AVOIR_POUR_INVENTAIRE ADD CONSTRAINT AV_INV_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE TRANSFERT_INTERENTREPOT ADD CONSTRAINT TRANS_SOURCE_FK 
    FOREIGN KEY (id_entrepot_SOURCE_TRANSFERT) REFERENCES ENTREPOT(id_entrepot);

ALTER TABLE TRANSFERT_INTERENTREPOT ADD CONSTRAINT TRANS_DEST_FK 
    FOREIGN KEY (id_entrepot_DEST_TRANSFERT) REFERENCES ENTREPOT(id_entrepot);

ALTER TABLE TRANSFERT_INTERENTREPOT ADD CONSTRAINT TRANS_MVMT_FK 
    FOREIGN KEY (id_mouvement_stock) REFERENCES MOUVEMENT_STOCK(id_mouvement_stock);

-- FK GESTION DES FOURNISSEURS
ALTER TABLE FOURNIR ADD CONSTRAINT FOURNIR_REF_FK 
    FOREIGN KEY (ref_fournisseur) REFERENCES FOURNISSEUR(ref_fournisseur);

ALTER TABLE FOURNIR ADD CONSTRAINT FOURNIR_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE COMMANDE_FOURNISSEUR ADD CONSTRAINT CDE_FOUR_REF_FK 
    FOREIGN KEY (ref_fournisseur) REFERENCES FOURNISSEUR(ref_fournisseur);

ALTER TABLE COMMANDE_FOURNISSEUR ADD CONSTRAINT CDE_FOUR_USER_FK 
    FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEURS(id_utilisateur);

ALTER TABLE AVOIR_STT_CDE ADD CONSTRAINT AV_STT_CDE_ID_FK 
    FOREIGN KEY (id_commande_four) REFERENCES COMMANDE_FOURNISSEUR(id_commande_four);

ALTER TABLE AVOIR_STT_CDE ADD CONSTRAINT AV_STT_CDE_STT_FK 
    FOREIGN KEY (id_statut_cde) REFERENCES STATUT_CDE_FOUR(id_statut_cde);

ALTER TABLE LIGNE_CDE_FOUR ADD CONSTRAINT LIGNE_CDE_FOUR_ID_FK 
    FOREIGN KEY (id_commande_four) REFERENCES COMMANDE_FOURNISSEUR(id_commande_four);

ALTER TABLE LIGNE_CDE_FOUR ADD CONSTRAINT LIGNE_CDE_FOUR_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE RECEPTION_CDE_FOUR ADD CONSTRAINT RECEPT_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE RECEPTION_CDE_FOUR ADD CONSTRAINT RECEPT_LIGNE_FK 
    FOREIGN KEY (id_ligne_cde_four) REFERENCES LIGNE_CDE_FOUR(id_ligne_cde_four);

-- FK GESTION DES CLIENTS
ALTER TABLE CLIENT ADD CONSTRAINT CLIENT_SEGMENT_FK 
    FOREIGN KEY (id_segment) REFERENCES SEGMENT_CLIENT(id_segment);

ALTER TABLE AVOIR_ADRESSE ADD CONSTRAINT AV_ADR_CLI_FK 
    FOREIGN KEY (email) REFERENCES CLIENT(email);

ALTER TABLE AVOIR_ADRESSE ADD CONSTRAINT AV_ADR_ADR_FK 
    FOREIGN KEY (id_adresse) REFERENCES ADRESSE_CLIENT(id_adresse);

ALTER TABLE COMPTE_FIDELITE ADD CONSTRAINT COMPTE_FID_CLI_FK 
    FOREIGN KEY (email) REFERENCES CLIENT(email);

ALTER TABLE HISTORIQUE_POINTS ADD CONSTRAINT HISTO_PTS_FID_FK1 
    FOREIGN KEY (id_compte_fid) REFERENCES COMPTE_FIDELITE(id_compte_fid);

ALTER TABLE HISTORIQUE_POINTS ADD CONSTRAINT HISTO_PTS_FID_FK2 
    FOREIGN KEY (num_fact_client) REFERENCES FACTURE_CLIENT(num_fact_client);

ALTER TABLE BON_REDUCTION ADD CONSTRAINT BON_REDUC_FID_FK 
    FOREIGN KEY (id_compte_fid) REFERENCES COMPTE_FIDELITE(id_compte_fid);

ALTER TABLE BON_REDUCTION ADD CONSTRAINT BON_REDUC_HISTO_FK 
    FOREIGN KEY (id_historique_pts_fid) REFERENCES HISTORIQUE_POINTS(id_historique_pts_fid);

ALTER TABLE APPLIQUER_BON_REDUC ADD CONSTRAINT APP_BON_REDUC_ID_FK 
    FOREIGN KEY (id_bon_reduction) REFERENCES BON_REDUCTION(id_bon_reduction);

ALTER TABLE APPLIQUER_BON_REDUC ADD CONSTRAINT APP_BON_REDUC_CDE_FK 
    FOREIGN KEY (num_cde_client) REFERENCES COMMANDE_CLIENT(num_cde_client);

-- FK GESTION DES COMMANDES
ALTER TABLE AVOIR_STATUT_CDE_CLIENT ADD CONSTRAINT AV_STT_CDE_CLI_NUM_FK 
    FOREIGN KEY (num_cde_client) REFERENCES COMMANDE_CLIENT(num_cde_client);

ALTER TABLE AVOIR_STATUT_CDE_CLIENT ADD CONSTRAINT AV_STT_CDE_CLI_ID_FK 
    FOREIGN KEY (id_statut_cde_client) REFERENCES STATUT_CDE_CLIENT(id_statut_cde_client);

ALTER TABLE COMMANDE_CLIENT ADD CONSTRAINT CDE_CLI_EMAIL_FK 
    FOREIGN KEY (email) REFERENCES CLIENT(email);

ALTER TABLE COMMANDE_CLIENT ADD CONSTRAINT CDE_CLI_ADR_LIV_FK 
    FOREIGN KEY (id_adresse_LIVRER_A) REFERENCES ADRESSE_CLIENT(id_adresse);

ALTER TABLE COMMANDE_CLIENT ADD CONSTRAINT CDE_CLI_ADR_FAC_FK 
    FOREIGN KEY (id_adresse_FACTURER_A) REFERENCES ADRESSE_CLIENT(id_adresse);

ALTER TABLE COMMANDE_CLIENT ADD CONSTRAINT CDE_CLI_USER_FK 
    FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEURS(id_utilisateur);

ALTER TABLE LIGNE_CDE_CLIENT ADD CONSTRAINT LIGNE_CDE_CLI_NUM_FK 
    FOREIGN KEY (num_cde_client) REFERENCES COMMANDE_CLIENT(num_cde_client);

ALTER TABLE LIGNE_CDE_CLIENT ADD CONSTRAINT LIGNE_CDE_CLI_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE LIGNE_CDE_CLIENT ADD CONSTRAINT LIGNE_CDE_CLI_ENT_FK 
    FOREIGN KEY (id_entrepot) REFERENCES ENTREPOT(id_entrepot);

ALTER TABLE GENERER_FACT ADD CONSTRAINT GEN_FACT_NUM_FK 
    FOREIGN KEY (num_fact_client) REFERENCES FACTURE_CLIENT(num_fact_client);

ALTER TABLE GENERER_FACT ADD CONSTRAINT GEN_FACT_CDE_FK 
    FOREIGN KEY (num_cde_client) REFERENCES COMMANDE_CLIENT(num_cde_client);

-- FK POLITIQUE TARIFAIRE & PROMOTIONS
ALTER TABLE PROMOTION ADD CONSTRAINT PROMO_TYPE_FK 
    FOREIGN KEY (id_type_promo) REFERENCES TYPE_PROMOTION(id_type_promo);

ALTER TABLE AVOIR_CONDITION_PROMO ADD CONSTRAINT AV_COND_C_FK 
    FOREIGN KEY (code_promo) REFERENCES PROMOTION(code_promo);

ALTER TABLE AVOIR_CONDITION_PROMO ADD CONSTRAINT AV_COND_I_FK 
    FOREIGN KEY (id_condition_promo) REFERENCES CONDITIONS_PROMO(id_condition_promo);

ALTER TABLE APPLIQUE_CDE_PROMO ADD CONSTRAINT APP_CDE_P_CODE_FK 
    FOREIGN KEY (code_promo) REFERENCES PROMOTION(code_promo);

ALTER TABLE APPLIQUE_CDE_PROMO ADD CONSTRAINT APP_CDE_P_NUM_FK 
    FOREIGN KEY (num_cde_client) REFERENCES COMMANDE_CLIENT(num_cde_client);

ALTER TABLE APPLIQUE_PROMO_CAT ADD CONSTRAINT APP_CAT_P_CAT_FK 
    FOREIGN KEY (id_cat_produit) REFERENCES CATEGORIE_PRODUIT(id_cat_produit);

ALTER TABLE APPLIQUE_PROMO_CAT ADD CONSTRAINT APP_CAT_P_CODE_FK 
    FOREIGN KEY (code_promo) REFERENCES PROMOTION(code_promo);

ALTER TABLE APPLIQUE_PROMO_MARQUE ADD CONSTRAINT APP_MARQ_P_MARQ_FK 
    FOREIGN KEY (id_marque) REFERENCES MARQUE(id_marque);

ALTER TABLE APPLIQUE_PROMO_MARQUE ADD CONSTRAINT APP_MARQ_P_CODE_FK 
    FOREIGN KEY (code_promo) REFERENCES PROMOTION(code_promo);

ALTER TABLE APPLIQUE_PROMO_CATALOG ADD CONSTRAINT APP_CTLG_P_CTLG_FK 
    FOREIGN KEY (id_catalogue) REFERENCES CATALOGUE(id_catalogue);

ALTER TABLE APPLIQUE_PROMO_CATALOG ADD CONSTRAINT APP_CTLG_P_CODE_FK 
    FOREIGN KEY (code_promo) REFERENCES PROMOTION(code_promo);

ALTER TABLE APPLIQUE_PROMO_PDT ADD CONSTRAINT APP_PDT_P_CODE_FK 
    FOREIGN KEY (code_promo) REFERENCES PROMOTION(code_promo);

ALTER TABLE APPLIQUE_PROMO_PDT ADD CONSTRAINT APP_PDT_P_SKU_FK 
    FOREIGN KEY (SKU_produit) REFERENCES PRODUIT(SKU_produit);

-- FK LOGISTIQUE & EXPEDITION
ALTER TABLE GRILLE_TARIFAIRE_TPS ADD CONSTRAINT GRILLE_TPS_TRANS_FK 
    FOREIGN KEY (id_transporteur) REFERENCES TRANSPORTEUR(id_transporteur);

ALTER TABLE COLIS ADD CONSTRAINT COLIS_USER_FK 
    FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEURS(id_utilisateur);

ALTER TABLE COLIS ADD CONSTRAINT COLIS_TRANS_FK 
    FOREIGN KEY (id_transporteur) REFERENCES TRANSPORTEUR(id_transporteur);

ALTER TABLE CONTENIR_COLIS ADD CONSTRAINT CONT_COLIS_NUM_FK 
    FOREIGN KEY (num_suivi_colis) REFERENCES COLIS(num_suivi_colis);

ALTER TABLE CONTENIR_COLIS ADD CONSTRAINT CONT_COLIS_LIGNE_FK 
    FOREIGN KEY (id_ligne_cde_client) REFERENCES LIGNE_CDE_CLIENT(id_ligne_cde_client);

ALTER TABLE PRIS_EN_CHARGE_TPS ADD CONSTRAINT PEC_TPS_COLIS_FK 
    FOREIGN KEY (num_suivi_colis) REFERENCES COLIS(num_suivi_colis);

ALTER TABLE PRIS_EN_CHARGE_TPS ADD CONSTRAINT PEC_TPS_TRANS_FK 
    FOREIGN KEY (id_transporteur) REFERENCES TRANSPORTEUR(id_transporteur);

/* 
HISTORIQUE DES EVENEMENTS DE SUIVI DES COLIS
Chaque ligne correspond a un evenement logistique associe a un colis :
pris_en_charge, en_transit, livre, etc.
*/
ALTER TABLE HISTORIQUE_EVENT_COLIS ADD CONSTRAINT HISTO_EVT_COLIS_NUM_FK 
    FOREIGN KEY (num_suivi_colis) REFERENCES COLIS(num_suivi_colis);

-- FK AVIS CLIENTS
ALTER TABLE AVIS_CLIENT ADD CONSTRAINT AVIS_CLIENT_EMAIL_FK 
    FOREIGN KEY (email) REFERENCES CLIENT(email);

ALTER TABLE AVIS_CLIENT ADD CONSTRAINT AVIS_CLIENT_VAR_FK 
    FOREIGN KEY (SKU_variante) REFERENCES VARIANTE(SKU_variante);

ALTER TABLE HISTORIQUE_MOD_AVIS ADD CONSTRAINT HISTO_MOD_AVIS_ID_FK 
    FOREIGN KEY (id_avis) REFERENCES AVIS_CLIENT(id_avis);

ALTER TABLE HISTORIQUE_MOD_AVIS ADD CONSTRAINT HISTO_MOD_TYPE_FK 
    FOREIGN KEY (id_type_mod_avis) REFERENCES MODERATION_AVIS(id_type_mod_avis);

ALTER TABLE HISTORIQUE_MOD_AVIS ADD CONSTRAINT HISTO_MOD_USER_FK 
    FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEURS(id_utilisateur);

SPOOL OFF ;